services:
  db:
    container_name: wallet-live-db
    image: postgres:18.1-alpine3.23
    environment:
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet_live
    ports:
      - "55432:5432"
    volumes:
      - wallet_live_pg:/var/lib/postgresql/data

volumes:
  wallet_live_pg: